### ISSUE TITLE
GPIO default on HIGH

### ISSUE THREAD

**Issue by Kunstflieger** [pfichtner/SipDoorbell#5]
GPIO Status is HIGH in default. Where can it changed to LOW

**Comment by pfichtner** [comment]
For which GPIO pin? This one? 
```
"name": "switch_gpiopin",
"label": "GPIO Pin switched HIGH when button press detected"
```

**Comment by pfichtner** [comment]
Please give https://github.com/pfichtner/SipDoorbell/releases/tag/0.1.2 a try

**Comment by Kunstflieger** [comment]
Thanks for this fast support!
I mean this one: 
`"label": "GPIO Pin to connect a push button which triggers a call"`

If I enter Pin e.g. "2" than it starts to ring until GPIO 2 is connected to ground (always closed). I want to use start ringing if GPIO 2 is connected to groun (always open).

**Comment by pfichtner** [comment]
Reopened since the fix doesn't solve the problem, will fix later

**Comment by pfichtner** [comment]
In my configuration I connected the push button to the digital pin and VCC, will have a look if I'll support your setup as well and how.

**Comment by pfichtner** [comment]
@Kunstflieger so which setup do you use?  
https://kalitut.com/raspberrypi-gpio-pull-up-pull-down-resistor/
I am using variant 4 so the pin get's high when the switch gets closed. If I understand you right your schematic is variant 3? So you want to have support for this variant, right?

**Comment by pfichtner** [comment]
@Kunstflieger Would you also have the need for support for the internal pullup?

**Comment by Kunstflieger** [comment]
I didn´t used a Pull-UP resistance. Just GPIO --> GND. So it makes sense to us a Pull-UP resistor and I will test it today.

**Comment by pfichtner** [comment]
@Kunstflieger I added support for pullup and pullup-internal as well. 
Please download and flash firmware.bin of https://github.com/pfichtner/SipDoorbell/actions/runs/5870078571

Now you can configure the input mode

| Mode | Description |
|-|-|
| PULLUP | Initiate call if input gets low, no internal pullup resistor |
| PULLUP (internal) | Initiate call if input gets low, internal pullup resistor |
| PULLDOWN |Initiate call if input gets high |

Haven't tried the image on my own, yet

**Comment by pfichtner** [comment]
Unfortunately no response from OP @Kunstflieger: Will close it without the knowledge if the PR fixes OP's problem or not
